@startuml

class Computadora{
-ram:int
-disco:int
-id:String
'el atributo contador va cambiando, es un atributo de clase
'para que sean compartidos para todos los objetos, esalgo para todos los objetos, por eso debe ser stático, cada computadora no cuenta,
{static} contador:int
+Computadora(ram:int,disco:int)
+toString():String
+gettersSetters()

}

class ComputadoraFactory{
-computadorasLigeras:Map<String,Computadora>
+getComputadora(ram:int,disco:int):Computadora

}

ComputadoraFactory -right->Computadora:listaComputadoras

@enduml