@startuml
'https://plantuml.com/sequence-diagram

interface IDescuento{
+descuento(tarjeta:Tarjeta,producto:Producto,cant:int)
}

class FacadeDescuento implements IDescuento{
-apiTarjeta:ApiTarjeta
-apiProducto:ApiProducto
-apiCantidad:ApiCantidad
+Constructor()
+descuento(tarjeta:Tarjeta,producto:Producto,cant:int)
}

class ApiCantidad{
+calcularDescuento(int cant):int
}

class ApiProducto{
+calcularDescuento(producto:Producto):int
}

class ApiTarjeta{
+calcularDescuento(tarjeta:Tarjeta):int
}

class Producto{

}

class Tarjeta{

}

ApiCantidad <-up-FacadeDescuento
ApiProducto <-up-FacadeDescuento
ApiTarjeta <-up-FacadeDescuento


@enduml